name = "fortran-scripts"
version = "0.1.0"
license = "license"
author = "Samuel Calderon"
maintainer = "samuelcalderon1202@hotmail.com"
copyright = "Copyright 2025, Samuel Calderon"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
